### PR TITLE
This is what I needed to do to get it working.

### PR DESCRIPTION
**Pull request by tlevine**

### CODE REVIEW

**Comment by goinnn** [comment]
Thanks!! I'll see it soon

**Comment by tlevine** [comment]
And it's the same as #69, #72, and #73 combined.

**Comment by tlevine** [comment]
Wow you're fast.

**Comment by goinnn** [comment]
Thanks a lot.

I'm sorry only several days :-)

**Comment by goinnn** [comment]
Fixed here 9fcdff3fe0b724869ec09476a9aea566de48bab9

**Pull request closed without merging**
